#!/usr/bin/env node
/**
 * Reads each example component source file and generates a _source.ts
 * module that exports the raw string. This keeps code tabs in the docs
 * app in sync with the actual source without manual maintenance.
 *
 * Run: node scripts/generate-sources.mjs
 */
import { readdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, basename } from 'node:path';

const EXAMPLES_DIR = 'projects/docs/src/app/examples';

const dirs = readdirSync(EXAMPLES_DIR, { withFileTypes: true })
  .filter((d) => d.isDirectory())
  .map((d) => d.name);

let generated = 0;

for (const dir of dirs) {
  const dirPath = join(EXAMPLES_DIR, dir);
  const files = readdirSync(dirPath).filter(
    (f) => f.endsWith('.component.ts') || f.endsWith('.component.html')
  );

  const tsFile = files.find((f) => f.endsWith('.component.ts'));
  if (!tsFile) continue;

  const entries = [];

  // Always include the TS source
  const tsSource = readFileSync(join(dirPath, tsFile), 'utf-8');
  entries.push({ name: tsFile, code: tsSource, language: 'typescript' });

  // If component uses templateUrl, include the HTML file too
  const htmlFile = files.find((f) => f.endsWith('.component.html'));
  if (htmlFile && tsSource.includes('templateUrl')) {
    const htmlSource = readFileSync(join(dirPath, htmlFile), 'utf-8');
    entries.push({ name: htmlFile, code: htmlSource, language: 'xml' });
  }

  const output = `// Auto-generated by scripts/generate-sources.mjs — do not edit
export const SOURCE_TABS = ${JSON.stringify(entries, null, 2)};
`;

  writeFileSync(join(dirPath, '_source.ts'), output);
  generated++;
}

console.log(`Generated ${generated} _source.ts files.`);
