name: CI
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: npm

      - name: Get branch name
        shell: bash
        run: echo "branch=$(echo ${GITHUB_REF##*/})" >> $GITHUB_OUTPUT
        id: branch

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Run semantic release and publish new version to npm
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm run semantic-release

      - name: Get last release
        id: version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: hjalmers
          repo: angular-generic-table
